name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with maven
        run: mvn clean test --file demo/pom.xml

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node modules
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm
        name: "Run frontend tests"
        run: cd front && npm run test
